### ISSUE TITLE
Spotify: keep original audio files

### ISSUE THREAD

**Issue by darealshinji** [Shabinder/SpotiFlyer#105]
I downgraded the app to v2.1 in order to download from Spotify. But I've discovered that it seems the songs are downloaded as m4a files and then converted to mp3, is that correct? In that case I would prefer an option to keep the original files, since I'm not stuck to hardware players that cannot play m4a/aac.

**Comment by Shabinder** [comment]
m4a files are without any metadata(like CoverArt, Song info, etc), that's why I delete those and keep mp3 after integrating metadata.

I want to have m4a files but unfortunately, there are no reliable m4a metadata taggers for some of the platforms we target.

and onward **2.2.x** , app download mp3 only, there is **NO** conversion done at client side.
