### ISSUE TITLE
Integrate Media Player into this App. 

### ISSUE THREAD

**Issue by Shabinder** [Shabinder/SpotiFlyer#113]
in IOS, all apps are sandboxed so no app can access our downloaded music, Hence for the User to be able to play all songs, We need to **Integrate a full-fledged Media** Player in Our app itself.

Plan:
 - Create Components for Media Screens 
   - 1) **Playlist/Track List Screen** (with DB support)
   - 2) **Play Screen** with functionality like seek,next song, prev. song, play all, shuffle, etc.
 
This is a **huge undertaking** of building a full-fledged Media Player with as much as shared code possible.

Any **Help** _(Both Contributions/ Donations)_ and **Suggestions** are most welcome!

**Comment by test2a** [comment]
On android at least, can we play music by streaming and saving the file along the way instead of waiting for full download and then using external players to play? That would be quit a usability thing

**Comment by Iamlooker** [comment]
You can my application Howl, It is completely written in Kotlin and Jetpack Compose.

I have a seperate module for [player-ui](https://github.com/Iamlooker/Howl/tree/alpha/player/ui-player) which depends slightly on [components](https://github.com/Iamlooker/Howl/tree/alpha/components)  module but should be ease to integrate in this project.

**Comment by test2a** [comment]
@Iamlooker that would be incredible because currently the app is pretty limited in functionality. you have to search, or can only download "favourited" ones. no way to play. 
i understand there is no "streaming" option in the app, you are expected to download music first but there is another app musify that only does streaming and you have to search for fresh stuff every time. 

spotiflyer + streaming+playback =best app.

**Comment by Iamlooker** [comment]
> spotiflyer + streaming+playback =best app.

Streaming would be a little tricky, plus currently my own repository is not stable.

For exoplayer streaming is pretty easy but adding such a huge part would increase app side by 3-4 mb.

Only the ui part is stable, and service and player are not currently optimized to be used on a production level app.

**Comment by test2a** [comment]
@Psych0somatic i understand your concern. here are my thoughts. the current UX on android at least is "not" great. you search and download a song or whatever. then you switch the app, open either the file manager and navigate to the folder and click on it or you open vlc player, wait for it to sync and then play. 

i currently do not have vlc installed so it doesnt even work.


compare this to a different app, "musify" https://github.com/Harsh-23/Musify and the issue becomes very apparent. here the user searches for something and clicks play. sure i understand the concern of app becoming big and difficult to maintain and such but why dont we have a UX whereby clicking on a downloaded song opens it in the default music player? i  mean i have installed "auxio" from f-droid and i expect that the app either plays it by itself or opens in a compatible player. i should not have to manually open the app, search for what i downloaded and then play that. 

can you play the audio in the app using the default audio player in the background so that the user doesnt leave spotiflyer and just stays here?

**Comment by Hashah2311** [comment]
### Hi, I am @Hashah2311
### As you have asked that you need a server so I recommend [this website](https://www.infinityfree.net/)
### I have used it, it uses only HTML, CSS & JavaScript files for website hosting and not any package like flask.
### If you want to, then you can checkout [my website](https://haxgamers.infinityfreeapp.com)
### Keep up the great work👍, Thank You

**Comment by ESCORPDROID2002** [comment]
could you show me how to download music from soundcloud please 🥺

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
