### ISSUE TITLE
WARNING FFmpeg not found at path

### ISSUE THREAD

**Issue by wigwoo1** [Shabinder/SpotiFlyer#1311]
After launching I get this error message. Songs still seem to download but have quite low quality even with setting set to 320kbps. Not sure what else to try. It sounds much better in Spotify for some reason
![image](https://user-images.githubusercontent.com/63259866/164754123-899df57e-a237-42fd-8503-5dd6955c07a4.png)

**Comment by wigwoo1** [comment]
Seems to only be the one specific song that sounded off so far

**Comment by dav01it** [comment]
The problem is explained in the console log ffmpeg is started with wrong arguments for loglevel:
`[AWT-EventQueue-0] INFO com.github.kokorin.jaffree.process.ProcessHandler - Starting process: ffmpeg
[AWT-EventQueue-0] INFO com.github.kokorin.jaffree.process.ProcessHandler - Waiting for process to finish
[StdErr] INFO com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader -` **Invalid loglevel "level+info"**`. Possible levels are numbers or:
"quiet"
"panic"
"fatal"
"error"
"warning"
"info"
"verbose"
"debug"
"trace"
[AWT-EventQueue-0] INFO com.github.kokorin.jaffree.process.ProcessHandler - Process has finished with status: 1
`

**Comment by dav01it** [comment]
Solved creating a "wrapper" for ffmpeg in /usr/local/bin (which is the first PATH for searching executables"

`nano /usr/local/bin/ffmpeg
`
insert this code:

```
#!/bin/bash
ARGS=$@
#echo $ARGS
NEWARGS="${ARGS/level+info/"info"}"
/usr/bin/ffmpeg $NEWARGS
```

save it

`chmod a+x /usr/local/bin/ffmpeg
`
