### ISSUE TITLE
Wrong songs downloaded

### ISSUE THREAD

**Issue by claraserlyn** [Shabinder/SpotiFlyer#188]
Not exactly wrong but I was trying to download the clean audio of an album but twice the app downloaded the explicit versions instead even though the links were the clean audio ones. This happened across 3 albums, is there any possibility for a fix? Thanks! Btw, appreciate this project you did alot! Keep up the amazing job 😁

https://open.spotify.com/album/7v7pe5vZQPWB5zW0JrKRiw?si=AEPj7ObzTuSkO_N9Ij756w&utm_source=copy-link&dl_branch=1

https://open.spotify.com/album/1DT6fDJL6AWPJxe7Lq1dPb?si=6mz6Bju9Qxq0fkIe76NdgQ&utm_source=copy-link&dl_branch=1

https://open.spotify.com/album/3VaaZ7OIbGLi60NVsnueoo?si=4IOSeLXBSA2wUka5Ve_Bfg&utm_source=copy-link&dl_branch=1

**Comment by kh9deir** [comment]
Sometimes I try to download the explicit audio and it does download the clean one.. is there is a way that you can choose what type you want to download ?

**Comment by hb-scope** [comment]
Same for crappy live versions

**Comment by Ammoswift** [comment]
Happened to me too Downloaded clean versions of dr.  dre songs and it just explicit versions.

**Comment by Reichsmania** [comment]
I have the same issue but instead of explicit songs downloading the clean ones. the issue I have is there are some songs especially some of the anime songs (ex. Attack on Titan previous OP songs) instead of downloading the original release it downloads the live performance version and one song Date A Live opening 1 it downloads a very different song. Somehow whenever I download normal music it just works fine.

Songs that are problematic/have issues on my part

https://open.spotify.com/track/0zvN9oq95bIEQjvfcdeZlX?si=4efe0f2f08f04eba

https://open.spotify.com/track/5uraJqtCBvLpwt3VeomZdq?si=b7dc3d976f824d00

https://open.spotify.com/track/4lHhlaay5sKaj3rcAHuwxb?si=a443921b3ba24db5

**Comment by LukysGaming** [comment]
+1, instead of clean version i get hardbass

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
