### ISSUE TITLE
Web UI not working

### ISSUE THREAD

**Issue by vpn12** [Shabinder/SpotiFlyer#88]
SpotiFlyer Web UI at "http://shabinder.github.io/SpotiFlyer/" is not working. After typing the name of the song in the search box, it keeps on loading.

Regards,
Vpn12

**Comment by Shabinder** [comment]
I am aware of that situation, the thing is I do run Web Server Proxy on my own setup, and it is **down** sometimes.

So if anybody has a server he might wanna share, I am happy to deploy proxy there. 
or people who can donate using the button on the Web-App homepage in order to help financially and in order to compensate web-server charges 

But for now there is nothing I can do.

**Comment by Shabinder** [comment]
@vpn12 check now , I just made it live again

**Comment by NitroNils** [comment]
Unfortunately same issue for me.

Pasting [link to spotify song](http://open.spotify.com/track/6zU5fZsPJtByjRjJRwrheR)  and hitting search yields eternal loading.

Firefox 89 on OpenBSD -CURRENT
